[build-system]
requires = ["setuptools>=61.0", "wheel"]  # Add setuptools and wheel here

[project]
name = "doubaoWord2Anki"
version = "0.1.0"
description = "Import JSON data to ANKI"
authors = [{name = "pony"}]
dependencies = [
    "requests>=2.28.0",
    "genanki>=0.13.0",
    "pydantic>=1.10.0",
    "python-dotenv>=0.21.0",
    "loguru>=0.6.0",
    "aiohttp>=3.8.0",
    "backoff>=2.2.0",
    "aiofiles>=23.1.0"
]


[project.scripts]
anki-importer = "doubaoWord2Anki.cli:main"
